apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-worker
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: worker-service-account
          containers:
          - name: worker
            image: onfinanceai/worker:latest
            envFrom:
            - secretRef:
                name: worker-secrets
            resources:
              requests:
                cpu: "200m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
          restartPolicy: OnFailure
